name: tf-nlp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - jupyter
  - pandas
  - scikit-learn
  - spacy        # ✅ Install via conda
  - pip:
      pip:
      - tensorflow-cpu==2.10.0
      - tensorflow-text==2.10.0
      - nltk
      - transformers==4.31.0
